server:
  port: 7001
eureka:
  instance:
    hostname: ls
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/ #这里是另一个中
spring:
  application:
    name: AIGOU-EUREKA